//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC_Assessment_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpNumber { get; set; }
        public string EmpName { get; set; }
        public string EmpSurname { get; set; }
        public System.DateTime EmpDOB { get; set; }
        public decimal EmpSalary { get; set; }
        public string RoleDesc { get; set; }
        public Nullable<int> ReportingLine { get; set; }
    }
}
